/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("aoc.kotlin-application-conventions")
}

dependencies {}

application {
    // Define the main class for the application.
    mainClass.set("aoc.app.AppKt")
}
